### ISSUE TITLE
Build Command Failed

### ISSUE THREAD

**Issue by solankiranvir** [helpdeveloper/AndroidFaceDetectOpenCV#1]
Hello Sir when i import this sample its fire this error:
Build command failed.
Error while executing process F:\AndroidStudio\android_sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build E:\CurentWork\AndroidFaceDetectOpenCV-master\AndroidFaceDetectOpenCV-master\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target native-lib}

ninja: error: '../../../../src/main/jniLibs/armeabi-v7a/libopencv_java3.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libnative-lib.so', missing and no known rule to make it

How to shortcut this issue? I didn't understand exact mistake.

**Comment by haroon47** [comment]
I am having same error. Please tell us the solution

**Comment by gbzarelli** [comment]
I will check, sorry for the delay, wait for news

**Comment by gbzarelli** [comment]
Hello guys,
I made several changes to the project including upgrading the version of the OpenCV SDK and Android. Please clone again the master and review the README for execution. Any questions just let me know. It is very important to follow the steps of the README mainly those listed below:

> - Make sure you have Android SDK up to date, with NDK installed
> - Download OpenCV SDK 3.4.3 for Android from OpenCV.org and decompress the zip file.
> - Clone this project
> - Create a symlink named jniLibs in app/src/main that points to ${YOUR_HOME_OPENCV_SDK}/sdk/native/libs
> - In app/CMakeLists.txt change line 9 to points to ${YOUR_HOME_OPENCV_SDK}/sdk/native/jni/include
> - Sync gradle
> -  Run the application
